"""empty message

Revision ID: 23fb2264a192
Revises: e8bf16a53069
Create Date: 2018-05-09 21:36:21.833269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fb2264a192'
down_revision = 'e8bf16a53069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bids',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('placed_by', sa.Integer(), nullable=True),
    sa.Column('bid_on_item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bid_on_item'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['placed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('users')
    # ### end Alembic commands ###
